### PR TITLE
feature: ASCII logo on server boot

### PR DESCRIPTION
**Pull request by mauricioabreu**
Solves #20

### CODE REVIEW

**Comment by mauricioabreu** [comment]
```
       _|\ _/|_,
     ,((\\``-\\\\_
   ,(())      `))\
 ,(()))       ,_ \
((())'   |        \
)))))     >.__     \
((('     /    `-. .c|
        /        `-`'
BoJack 0.1.0
[bojack][127.0.0.1:5000][2016-08-28 23:36:03 -0300][INFO] Server started at 127.0.0.1:5000
```

**Comment by mauricioabreu** [comment]
I don't like this code. Just saying...
I am reading from a file because I don't know how to just "puts <ascii_art_here"

Also tests failing because

```
Error in ./spec/spec_helper.cr:5: instantiating 'BoJack::Server#start()'

  BoJack::Server.new("127.0.0.1", 5000, fake_logger).start
                                                     ^~~~~

in ./src/bojack/server.cr:24: undefined constant BoJack::VERSION

      puts "BoJack #{BoJack::VERSION}"
                     ^~~~~~~~~~~~~~~
```

**Comment by marceloboeira** [comment]
@mauricioabreu I rather a file read than having the ASCII in the source file, the only thing is we have a lot of different code in the server class, maybe create a class that reads the file and "generates" the logo for the initializer. About the error, you have to make sure you require `src/bojack/version.cr` file to have access to the VERSION constant.

**Comment by mauricioabreu** [comment]
@marceloboeira I updated the code. Not sure if it is good now.

**Comment by marceloboeira** [comment]
@mauricioabreu it is better, thanks!

**Pull request merged**
