### PR TITLE
fix: Remove dependency lock

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by marceloboeira** [comment]
@mauricioabreu why? BoJack is supposed to be an application, not a library, that said it must have the dependency lock in order to install the correct dependencies on build.

**Comment by mauricioabreu** [comment]
You are right! Closing.

**Comment by marceloboeira** [comment]
@mauricioabreu 😛

**Comment by mauricioabreu** [comment]
:P

**Pull request closed without merging**
