### PR TITLE
feature: allowing manage lists Append / Pop

### PR DESCRIPTION
**Pull request by cristianoliveira**
Implementation to allow manage lists / stacks using append and pop.

Get: returns a list or value
Set: accepts value/values separated by comma 
Append: add the value/values to the end of the list
Pop: retrieve and delete the last item

### CODE REVIEW

**Comment by marceloboeira** [comment]
@cristianoliveira I will take a look at it next week, if you feel like it merge into Master, seems ok :)

**Comment by mauricioabreu** [comment]
It is hard to tell if there is something wrong here. Your code is clean, well designed and functional.
Also the feature is worth these lines.  Good job!

**Comment by cristianoliveira** [comment]
Thanks guys.

I did this PR just because is kind of a big change that modifies the behavior of `get` and `set` commands. So I thought was a good idea to have a code review.

**Comment by marceloboeira** [comment]
@cristianoliveira merged!

**Comment by cristianoliveira** [comment]
:)

**Pull request closed without merging**
