### PR TITLE
doc: Update the license date

### PR DESCRIPTION
**Pull request by marceloboeira**

### CODE REVIEW

**Review by mauricioabreu — APPROVED** [review]

**Review by hugoabonizio — APPROVED** [review]
Long time no see :smile:

**Comment by marceloboeira** [comment]
hey @hugoabonizio, I have been studying other things for a while. but I plan to do some work on bojack next year.

BTW: I am running some tests with github hooks, don't merge the PR guys hehehe

**Comment by hugoabonizio** [comment]
Nice to hear that @marceloboeira! I want to get back to work on bojack soon too :smiley:

**Comment by marceloboeira** [comment]
@hugoabonizio I have considered rewriting it in Haskell, but I guess I already have some personal feelings for the crystal code here. So, I will start another similar project with Haskell, probably I will call it Todd, since the idea is to be "pure" (given the constraints of the 3rd season, but no spoilers).

**Comment by hugoabonizio** [comment]
@marceloboeira This's a really nice name :rofl:

You can call it Hollyhock Manheim-Mannheim-Guerrero-Robinson-Zilberschlag-Hsung-Fonzerelli-McQuack too, given the relation with BoJack (spoiler?)

**Comment by marceloboeira** [comment]
@hugoabonizio true ahaha but it is not as Pure as Todd ahaha

**Comment by mauricioabreu** [comment]
did I just read BoJack's spoilers on Github? hahahaha oh fuck xD

**Comment by marceloboeira** [comment]
@mauricioabreu you have to be realistic when you read PRs from a project called BoJack ahahah

**Comment by mauricioabreu** [comment]
@marceloboeira hahahaha you are right! Don't create a project called MindHunter, please :P

**Comment by marceloboeira** [comment]
@mauricioabreu I haven't started watching it yet ahahha

**Comment by marceloboeira** [comment]
btw, dont look at the PRs on http://github.com/feedcast hahah

**Comment by mauricioabreu** [comment]
@marceloboeira hahahahaha I feel safe now

**Comment by hugoabonizio** [comment]
Sorry @mauricioabreu hahahah :laughing:

**Pull request merged**
