### PR TITLE
refactor: Make Logger a Singleton

### PR DESCRIPTION
**Pull request by mauricioabreu**

### CODE REVIEW

**Comment by mauricioabreu** [comment]
I don't know to implement this pattern in Crystal/Ruby. I tried.
I am without internet connection here (actually I have 3g but it sucks badly) so it is hard to read about good implementations (thanks for the link anyways @marceloboeira )

**Comment by marceloboeira** [comment]
@mauricioabreu the Singleton approach is not bad, but there some regards over the rest:
- `BoJack::Logger` would be a better name, remember to call the std logger by `::Logger`, to force the lookup. 
- Instead of returning the bojack logger in the `instance` why don't you return the Logger itself? (in order to prevent `logger.log`.

Let me know if you have any questions on this.

Usage: 
- First time (could be in the server or the CLI)
  `BoJack::Logger.instance(hostname: foo, port: bar)`
- Usage for the rest of the project:
  `@logger = BoJack::Logger.instance`

Always remember that crystal has method overloading, which can be handful for these kind of situations.
https://crystal-lang.org/docs/syntax_and_semantics/overloading.html

**Comment by mauricioabreu** [comment]
@marceloboeira Made a new commit.
I think the `self.instance` can not return a Crystal Logger instance because this way `instance.new` will not work.

**Comment by mauricioabreu** [comment]
I will try to implement overloading here. Thanks!

**Comment by marceloboeira** [comment]
I have made some adjustments but I will give you the credits in the commit message!

**Comment by mauricioabreu** [comment]
No problem! Thanks!

**Pull request closed without merging**
